#profile
spring:
  datasource:
    url: jdbc:mysql://localhost/jdbc_test?allowMultiQueries=true&useSSL=false
    username: root
    password: test_okcoin
    driver-class-name: com.mysql.jdbc.Driver

# Number of ms to wait before throwing an exception if no connection is available.
    tomcat:
      max-wait: 10000
# Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 50
# Validate the connection before borrowing it from the pool.
      test-on-borrow: true

server:
  port: 8000

logging:
  path: logs