server:
  port: 2371

management:
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        exclude: beans,info
        include: '*'
    web:
      exposure:
        exclude: beans
        include: '*'